### ISSUE TITLE
Client Crash - breaking randomite ore.

### ISSUE THREAD

**Issue by ProsperCraft** [kegare/Cavern2#11]
I first had this after cavern tweaks installed, but even after removing it, I am still getting it.

https://gist.github.com/ProsperCraft/bba20365c4dd24e7ccc3f59a5a2fb5e7

Another player on the server- 

https://pastebin.com/wdDU1gGb

Another player- he said he was ok breaking one at a time, but once he broke two at a time he got the crash.
https://pastebin.com/y1AHfG6p

**Comment by alxcool** [comment]
Hi! Since I'm not sure if My crash duplicate this issue, I will share the link ;) I may have more info on how to reproduce, but like some others I should launch some test when I run cavern 2 alone.

There is the link
https://github.com/kegare/Cavern2/issues/17
and my past bin
https://paste.dimdev.org/vafofabewi.txt

**Comment by kegare** [comment]
This issue is expired.
