### ISSUE TITLE
Teleport endless Loop

### ISSUE THREAD

**Issue by Shu89** [kegare/Cavern2#43]
After Enter a Portal you get Teleportet all the time - hang inside a endless loop. Dosnt matter what world it is.
Last Version - its kind strange.

**Comment by Shudragon** [comment]
can confirm, am also looping until i hit disconnect and then show up either on top of the portal or several blocks away. strange.

using RAD modpack 1.24

**Comment by SyncStelar** [comment]
I'm also using the RAD modpack and sneaking stops you from teleporting through the portal.

**Comment by C0LiSii0N** [comment]
Still bugged, pressing shift at the exact moment when you connect to the new dimension fix it but still pretty anoying

**Comment by DamnitDevil** [comment]
Still occurring for me as well. Can confirm sneak works. Coming out, even sneaking, is obnoxious still and kinda difficult.

**Comment by LokiwanKenobi** [comment]
Hello. We have a server Running RAD with this mod. One of our members is having this issue. @kegare do you plan on addressing this soon? It seems this is an ongoing issue with several servers and members. 

Our member tries to enter the portal and then is "stuck in an infinite loop" of teleportation until the portal kicks him back out in the over world. 

If you could respond please, that would be great. This has been an issue posted here since your most recent update in May 2019

**Comment by DerpTheBugbear** [comment]
This is still a big problem.  Mod is nearly unusable in this state.

**Comment by ProsperCraft** [comment]
https://github.com/kegare/Cavern2/issues/23

**Comment by kegare** [comment]
This issue is expired.
